[game]
window_title = "Monster Hunter Wilds"

[ocr]
lang = "japan"

[coordinates]
auto_select_btn = [ 0.09688, 0.98403,]
reroll_btn = [ 0.17969, 0.53681,]
skill_area = [ 0.83984, 0.49306, 1.0, 0.55556,]
back_btn = [ 0.01562, 0.98542,]
material_rows = [ [ 0.26562, 0.23611, 0.35938, 0.27083,], [ 0.26562, 0.31944, 0.35938, 0.35417,], [ 0.26562, 0.40278, 0.35938, 0.4375,],]
weapon_name = [ 0.63281, 0.175, 0.78906, 0.21042,]
weapon_element = [ 0.69922, 0.38889, 0.79297, 0.41667,]

[keybinds]
auto_select_key = "g"
confirm_key = "space"
cancel_key = "esc"
up_key = "up"
down_key = "down"
menu_key = "esc"
tab_left_key = "q"
stop_key = "alt+q"

[delays]
after_click = 0.2
reroll_animation = 5.0
return_to_title = 0.3

[output]
dir = "data/output/skill_reroller"
report_name = "report"
table_file_name = "reroll_table.csv"

[reroll]
max_attempts = 0
match_threshold = 0.65
stop_on_match = false
return_to_title = true
current_confirmed_count = 0
target_combinations = [ [ "巨戟龍の黙示録", "ヌシの魂",], [ "黒蝕竜の力", "ヌシの魂",],]

[selection]
weapons = [ "大剣", "太刀", "片手剣", "双剣", "ハンマー", "狩猟笛", "ランス", "ガンランス", "スラッシュアックス", "チャージアックス", "操虫棍", "ライトボウガン", "ヘビィボウガン", "弓",]
elements = [ "火", "水", "雷", "氷", "龍", "毒", "麻痺", "睡眠", "爆破", "無",]
last_weapon = "大剣"
last_element = "火"

[skills]
series = [ "闢獣の力", "火竜の力", "兇爪竜の力", "鎖刃竜の命脈", "波衣竜の守護", "煌雷竜の力", "雷顎竜の闘志", "雪獅子の闘志", "鎧竜の守護", "凍峰竜の反逆", "暗器蛸の力", "獄焔蛸の反逆", "黒蝕竜の力", "鎖刃竜の飢餓", "泡狐竜の力", "白熾龍の脈動", "千刃竜の闘志", "海竜の渦雷", "暗黒騎士の証", "オメガレゾナンス", "巨戟龍の黙示録",]
group = [ "鱗張りの技法", "革細工の柔性", "毛皮の昂揚", "甲虫の知らせ", "護竜の脈動", "ヌシの誇り", "甲虫の擬態", "革細工の滑性", "鱗重ねの工夫", "毛皮の誘惑", "護竜の守り", "ヌシの憤激", "先達の導き", "ヌシの魂",]
